# Generated by Django 3.0 on 2021-08-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
