# Generated by Django 3.0 on 2021-08-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210811_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='basicpic.png', null=True, upload_to=''),
        ),
    ]
